name: 'EzContent base'
description: "Enable base themes and configuration. Meant as a lighter base than the default installation profile"
type: 'Setup'

# Modules to install to support the profile.
install:
  - admin_toolbar_tools
  - block_content
  - breakpoint
  - ckeditor5
  - color
  - comment
  - config
  - config_rewrite
  - contact
  - content_lock_timeout
  - contextual
  - crop
  - dblog
  - editor
  - email_registration
  - entity_embed
  - field_ui
  - file
  - formtips
  - fvm
  - gin_login
  - gin_toolbar
  - google_analytics
  - help
  - history
  - media
  - image
  - image_widget_crop
  - linkit
  - moderation_dashboard
  - moderation_sidebar
  - options
  - path
  - pathauto
  # Install primary module.
  - password_policy
  # Install submodules.
  - password_policy_characters
  - password_policy_history
  - password_policy_length
  - quickedit
  - rdf
  - redirect
  - robotstxt
  - scheduler_content_moderation_integration
  - schema_metatag
  - search
  - shortcut
  - simple_sitemap
  - smart_trim
  - social_media_links
  - taxonomy
  - toolbar
  - update_helper_checklist
  - views
  - views_ui
  - vertical_tabs_config
  - workflows
  - gin







